export const lang = {
  en: {
    learnFinance: "Learn Finance",
    greeting: "Hi, ",
    login: "Login",
    loginAsGuest: "Login with Guest account",
    loginText: "Already have an account? Login now!",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    password: "Password",
    signup: "Create my account",
    signupText: "Don't have an account? Signup now!",
    books: "Books",
    wishlist: "Wishlist",
    cart: "Cart",
    options: "Options Trading",
    technical: "Technical Analysis",
    value: "Value Investing",
    all: "Show all",
    trending: "Trending",
    addToCart: "Add to Cart",
    outOfStock: "Out of Stock",
    includeOutOfStock: "Include Out of Stock",
    sortBy: "Sort By",
    lowToHigh: "Price - Low to high",
    highToLow: "Price - High to low",
    reset: "Reset",
    filter: "Filter",
    summary: "Summary",
    checkout: "Checkout",
    total: "Total",
    emptyCart: "Your cart is empty",
    emptyWishlist: "Your wishlist is empty",
    goShopping: "Go Shopping"
  },
  hi: {
    learnFinance: "लर्न फाइनेंस",
    greeting: "नमस्ते, ",
    login: "साइन-इन करें",
    loginAsGuest: "अतिथि के रूप में लॉगिन करें",
    loginText: "पहले से ही एक अकाउंट है? अभी लॉगिन करें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signup: "मेरा अकाउंट बनाएं",
    signupText: "अकाउंट नहीं है? अकाउंट बनाएं",
    books: "पुस्तकें",
    wishlist: "इच्छा-सूची",
    cart: "कार्ट",
    options: "ऑप्शन ट्रेडिंग",
    technical: "टेक्निकल एनालिसिस",
    value: "वैल्यू इन्वेस्टिंग",
    all: "सभी कैटेगरी",
    trending: "चर्चित",
    addToCart: "कार्ट में डालें",
    outOfStock: "स्टॉक ख़त्म",
    includeOutOfStock: "स्टॉक में नहीं शामिल करें",
    sortBy: "छांटें",
    lowToHigh: "मूल्य - कम से अधिक",
    highToLow: "मूल्य - अधिक से कम",
    reset: "रीसेट",
    filter: "फ़िल्टर",
    summary: "सारांश",
    checkout: "चेक आउट",
    total: "संपूर्ण",
    emptyCart: "आपकी कार्ट खाली है",
    emptyWishlist: "आपकी इच्छा-सूची खाली है",
    goShopping: "किताबें देखें"
  }
};
